<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="eapfukl325" name="Default test" tests="1" failures="0" timestamp="22 Jan 2013 14:15:00 GMT" time="0.23" errors="0">
  <testcase name="@BeforeMethod startCalabashDriverServer" time="0.0" classname="sh.calaba.calabashdriver.Pickerjavatest">
    <failure type="java.lang.AssertionError" message="The local calabash-driver server cannot be started: ">
      <![CDATA[java.lang.AssertionError: The local calabash-driver server cannot be started: 
	at org.testng.Assert.fail(Assert.java:83)
	at sh.calaba.calabashdriver.Pickerjavatest$DriverServerRunnable.run(Pickerjavatest.java:75)
	at java.lang.Thread.run(Thread.java:662)
	at sh.calaba.calabashdriver.Pickerjavatest.startCalabashDriverServer(Pickerjavatest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:564)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:213)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:653)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.run(TestNG.java:1036)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: sh.calaba.utils.AdbConnetionException: Exit value of process was 1 but expected 0
	at sh.calaba.utils.DefaultAdbConnection.confirmExitValueIs(DefaultAdbConnection.java:111)
	at sh.calaba.utils.DefaultAdbConnection.runProcess(DefaultAdbConnection.java:79)
	at sh.calaba.driver.utils.CalabashAdbCmdRunner.installAPKFile(CalabashAdbCmdRunner.java:133)
	at sh.calaba.driver.server.CalabashProxy.doIinitializeMobileDevices(CalabashProxy.java:157)
	at sh.calaba.driver.server.CalabashProxy.access$000(CalabashProxy.java:45)
	at sh.calaba.driver.server.CalabashProxy$1.run(CalabashProxy.java:80)
	at java.lang.Thread.run(Thread.java:662)
	at sh.calaba.driver.server.CalabashProxy.initializeMobileDevices(CalabashProxy.java:78)
	at sh.calaba.driver.server.CalabashAndroidServer.start(CalabashAndroidServer.java:113)
	at sh.calaba.calabashdriver.Pickerjavatest$DriverServerRunnable.run(Pickerjavatest.java:72)
	... 28 more
]]>
    </failure>
  </testcase> <!-- @BeforeMethod startCalabashDriverServer -->
  <testcase name="@AfterMethod shutdown" time="0.0" classname="sh.calaba.calabashdriver.Pickerjavatest">
    <skipped/>
  </testcase> <!-- @AfterMethod shutdown -->
  <testcase name="testPicker" time="0.0010" classname="sh.calaba.calabashdriver.Pickerjavatest">
    <skipped/>
  </testcase> <!-- testPicker -->
</testsuite> <!-- Default test -->
